### ISSUE TITLE
errors in collection listing at PermissionsServiceImpl.resolveMostPermissiveAccessForUser(PermissionsServiceImpl.java:340)

### ISSUE THREAD

**Issue by michael-conway** [irods-contrib/metalnx-web#105]
see attached log info, caused by collection listing in metalnx

```


2019-05-31 16:38:11 INFO  GenQueryProcessor:121 - auto closing result set
2019-05-31 16:38:11 INFO  GenQueryProcessor:154 - getting more results for query
2019-05-31 16:38:11 INFO  CollectionAOHelper:148 - collection built

2019-05-31 16:38:11 INFO  CollectionAOHelper:149 - Collection [collectionId=34602, collectionName=/xxxZone/home/foo, objectPath=, collectionParentName=/xxxZone/home, collectionOwnerName=foo, collectionOwnerZone=xxxZone, collectionMapId=0, collectionInheritance=, comments=, info1=, info2=, createdAt=Tue Apr 12 19:53:45 GMT 2011, modifiedAt=Tue Apr 12 19:53:45 GMT 2011, specColType=NORMAL, isProxy=false]
2019-05-31 16:38:11 DEBUG PermissionsServiceImpl:424 - Getting permission info for collection /xxxZone/home/foo
2019-05-31 16:38:11 INFO  CollectionAOImpl:1882 - listPermissionsForCollection: /xxxZone/home/foo
2019-05-31 16:38:11 INFO  CollectionListingUtils:1179 - ObjStat [absolutePath=/xxxZone/home/foo, objectPath=, objectType=COLLECTION, dataId=34602, checksum=, ownerName=foo, ownerZone=xxxZone, objSize=0, createdAt=Tue Apr 12 19:53:45 GMT 2011, modifiedAt=Tue Apr 12 19:53:45 GMT 2011, specColType=NORMAL, collectionPath=, cacheDir=, cacheDirty=false, replNumber=0, standInGeneratedObjStat=false]
2019-05-31 16:38:11 INFO  CollectionAOImpl:1898 - specific query supported looking for ShowCollAcls
2019-05-31 16:38:11 INFO  SpecificQueryAOImpl:133 - findSpecificQueryByAlias()
2019-05-31 16:38:11 INFO  SpecificQueryAOImpl:145 - alias:ShowCollAcls
2019-05-31 16:38:11 INFO  SpecificQueryAOImpl:146 - zoneHint:xxxZone
2019-05-31 16:38:11 INFO  SpecificQueryAOImpl:372 - executeSpecificQueryUsingAlias()
2019-05-31 16:38:11 INFO  QueryResultProcessingUtils:57 - rows returned from iRODS query: 1
2019-05-31 16:38:11 INFO  SpecificQueryAOImpl:590 - closeResultSet()
2019-05-31 16:38:11 INFO  CollectionAOImpl:1909 - querying via specific query
2019-05-31 16:38:11 INFO  SpecificQueryAOImpl:430 - executeSpecificQueryUsingAlias()
2019-05-31 16:38:11 INFO  SpecificQueryAOImpl:133 - findSpecificQueryByAlias()
2019-05-31 16:38:11 INFO  SpecificQueryAOImpl:145 - alias:ShowCollAcls
2019-05-31 16:38:11 INFO  SpecificQueryAOImpl:146 - zoneHint:
2019-05-31 16:38:11 INFO  SpecificQueryAOImpl:372 - executeSpecificQueryUsingAlias()
2019-05-31 16:38:11 INFO  QueryResultProcessingUtils:57 - rows returned from iRODS query: 1
2019-05-31 16:38:11 INFO  SpecificQueryAOImpl:590 - closeResultSet()
2019-05-31 16:38:11 INFO  QueryResultProcessingUtils:57 - rows returned from iRODS query: 1
2019-05-31 16:38:11 INFO  SpecificQueryAOImpl:590 - closeResultSet()
2019-05-31 16:38:11 ERROR BrowseController:253 - exception getting coll browser view
com.emc.metalnx.core.domain.exceptions.DataGridException: general data grid exception
        at com.emc.metalnx.services.irods.PermissionsServiceImpl.resolveMostPermissiveAccessForUser(PermissionsServiceImpl.java:340)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:333)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:190)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
        at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:99)
        at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:282)
        at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
        at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:213)
        at com.sun.proxy.$Proxy51.resolveMostPermissiveAccessForUser(Unknown Source)
        at com.emc.metalnx.controller.BrowseController.getCollBrowserView(BrowseController.java:946)
        at com.emc.metalnx.controller.BrowseController.getSubDirectories(BrowseController.java:251)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205)
        at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:133)
        at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:97)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:827)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:738)
        at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85)
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:967)
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:901)
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)
        at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:872)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:661)
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330)
        at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:118)
        at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:84)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
        at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:113)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
        at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:103)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
        at org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:113)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
        at org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:154)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
        at org.springframework.security.web.savedrequest.RequestCacheAwareFilter.doFilter(RequestCacheAwareFilter.java:45)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
        at org.springframework.security.web.authentication.www.BasicAuthenticationFilter.doFilter(BasicAuthenticationFilter.java:150)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
        at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:199)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
        at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:110)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
        at org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:50)
```

**Comment by michael-conway** [comment]
so far not reproducible...added extra logging for a retest and log capture

**Comment by michael-conway** [comment]
will close this issue as not reproduced.
