### ISSUE TITLE
hibernate error: column t1.tgconstrname does not exist - caused by outdated postgresql dependency

### ISSUE THREAD

**Issue by yrro** [irods-contrib/metalnx-web#197]
I'm seeing this with the `2.2.0` docker image:

```
2021-02-18 16:24:02 INFO  Dialect:145 - HHH000400: Using dialect: org.hibernate.dialect.PostgreSQLDialect
2021-02-18 16:24:02 INFO  LobCreatorBuilder:123 - HHH000424: Disabling contextual LOB creation as createClob() method threw error : java.lang.reflect.InvocationTargetException
2021-02-18 16:24:02 INFO  TransactionFactoryInitiator:62 - HHH000399: Using default transaction strategy (direct JDBC transactions)
2021-02-18 16:24:02 INFO  ASTQueryTranslatorFactory:47 - HHH000397: Using ASTQueryTranslatorFactory
2021-02-18 16:24:02 INFO  Version:30 - HV000001: Hibernate Validator 5.3.5.Final
2021-02-18 16:24:03 INFO  SchemaUpdate:207 - HHH000228: Running hbm2ddl schema update
2021-02-18 16:24:03 INFO  SchemaUpdate:218 - HHH000102: Fetching database metadata
2021-02-18 16:24:03 INFO  SchemaUpdate:230 - HHH000396: Updating schema
2021-02-18 16:24:03 WARN  SqlExceptionHelper:144 - SQL Error: 0, SQLState: 42703
2021-02-18 16:24:03 ERROR SqlExceptionHelper:146 - ERROR: column t1.tgconstrname does not exist
  Position: 113
2021-02-18 16:24:03 ERROR SchemaUpdate:272 - HHH000299: Could not complete schema update
java.lang.NullPointerException
	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:126)
        [...]	at java.base/java.lang.Thread.run(Thread.java:834)
```

PostgreSQL logs the following:

```
2021-02-18 16:24:03.582 UTC [25039] ERROR:  column t1.tgconstrname does not exist at character 113
2021-02-18 16:24:03.582 UTC [25039] STATEMENT:  SELECT DISTINCT NULL::text as pnspname, NULL::text as fnspname, c1.relname as prelname, c2.relname as frelname, t1.tgconstrname, a.attnum as keyseq, ic.relname as fkeyname, t1.tgdeferrable, t1.tginitdeferred, t1.tgnargs,t1.tgargs, p1.proname as updaterule, p2.proname as deleterule  FROM pg_class c1  JOIN pg_index i ON (c1.oid=i.indrelid)  JOIN pg_class ic ON (i.indexrelid=ic.oid)  JOIN pg_attribute a ON (ic.oid=a.attrelid),  pg_class c2,  pg_trigger t1  JOIN pg_proc p1 ON (t1.tgfoid=p1.oid),  pg_trigger t2  JOIN pg_proc p2 ON (t2.tgfoid=p2.oid) WHERE (t1.tgrelid=c1.oid AND t1.tgisconstraint AND t1.tgconstrrelid=c2.oid AND p1.proname ~ '^RI_FKey_.*_upd$') AND (t2.tgrelid=c1.oid AND t2.tgisconstraint AND t2.tgconstrrelid=c2.oid AND p2.proname ~ '^RI_FKey_.*_del$') AND i.indisprimary AND c2.relname='metadata_fields' ORDER BY prelname,keyseq
```

The `tgconstrname` colum in the `pg_trigger` table last appeared in [PostgreSQL 8.4](https://www.postgresql.org/docs/8.4/catalog-pg-trigger.html)! It's gone in [9.0](https://www.postgresql.org/docs/9.0/catalog-pg-trigger.html).

Would it be possible to update the dependency?

**Comment by yrro** [comment]
FYI, I repacked `metalnx.war`, removing `WEB-INF/lib/postgresql-8.4-702.jdbc4.jar` and adding `https://repo1.maven.org/maven2/org/postgresql/postgresql/42.2.18/postgresql-42.2.18.jar` in its place, and Metalnx seems to work OK.

**Comment by trel** [comment]
Thanks for the writeup.     I saw this just yesterday as well.

I fixed it locally by using the `postgres:11` image in my `docker-compose.yml` rather than `postgres:latest` which now uses 12 and is very angry about the t1.tgconstrname column.

```
  db:
    image: postgres:11
```

**Comment by yrro** [comment]
Odd, `tgconstrname` was removed in 9.0 according to https://pgpedia.info/p/pg_trigger.html ... that's why I didn't bother with an earlier version!

On the other hand it seemed odd at the time that no one had tried running Metalnx with a newer version of PostgreSQL... 8.4 is quite old!

**Comment by trel** [comment]
We plan to remove the Metalnx database entirely in the future.

Closing this for now as sufficiently fixed :)
