### ISSUE TITLE
metalnx-web 1.3.0 throws exception on startup

### ISSUE THREAD

**Issue by kuntzagk** [irods-contrib/metalnx-web#20]
Hi, 

when starting a freshly installed 1.3.0 I see an exception in the log file.
I'm quite sure there was no typo in the password (ran the setup script 3 times)

irods.environment.properties:
```
irods.host=localhost
irods.port=1247
irods.zoneName=testZone
irods.auth.scheme=STANDARD

# Jobs parameters
jobs.irods.username=rods
jobs.irods.password=XXXXXX
jobs.irods.auth.scheme=STANDARD
runSyncJobs=true

# HTTP connection for RMD
rmd.connection.timeout=500
rmd.connection.port=8000

# Reverse DNS lookup on dashboard
reverse.dns.lookup=false
```
This is the exception:

```
2017-06-30 16:48:08 ERROR AbstractIRODSMidLevelProtocolFactory:245 - authentication exception, will close iRODS connection and re-throw
org.irods.jargon.core.exception.AuthenticationException: PAM authentication error
        at org.irods.jargon.core.connection.IRODSErrorScanner.checkSpecificCodesAndThrowIfExceptionLocated(IRODSErrorScanner.java:208)
        at org.irods.jargon.core.connection.IRODSErrorScanner.inspectAndThrowIfNeeded(IRODSErrorScanner.java:123)
        at org.irods.jargon.core.connection.AbstractIRODSMidLevelProtocol.processMessageInfoLessThanZero(AbstractIRODSMidLevelProtocol.java:1232)
        at org.irods.jargon.core.connection.AbstractIRODSMidLevelProtocol.readMessage(AbstractIRODSMidLevelProtocol.java:724)
        at org.irods.jargon.core.connection.AbstractIRODSMidLevelProtocol.readMessage(AbstractIRODSMidLevelProtocol.java:690)
        at org.irods.jargon.core.connection.IRODSMidLevelProtocol.irodsFunction(IRODSMidLevelProtocol.java:220)
        at org.irods.jargon.core.connection.AbstractIRODSMidLevelProtocol.irodsFunction(AbstractIRODSMidLevelProtocol.java:176)
        at org.irods.jargon.core.connection.AbstractIRODSMidLevelProtocol.irodsFunction(AbstractIRODSMidLevelProtocol.java:572)
        at org.irods.jargon.core.connection.PAMAuth.processAuthenticationAfterStartup(PAMAuth.java:69)
        at org.irods.jargon.core.connection.AuthMechanism.authenticate(AuthMechanism.java:217)
        at org.irods.jargon.core.connection.AbstractIRODSMidLevelProtocolFactory.authenticate(AbstractIRODSMidLevelProtocolFactory.java:241)
        at org.irods.jargon.core.connection.AbstractIRODSMidLevelProtocolFactory.instance(AbstractIRODSMidLevelProtocolFactory.java:103)
        at org.irods.jargon.core.connection.IRODSProtocolManager.createNewProtocol(IRODSProtocolManager.java:146)
        at org.irods.jargon.core.connection.IRODSSimpleProtocolManager.getIRODSProtocol(IRODSSimpleProtocolManager.java:69)
        at org.irods.jargon.core.connection.IRODSSession.connectAndAddToProtocolsMap(IRODSSession.java:511)
        at org.irods.jargon.core.connection.IRODSSession.currentConnection(IRODSSession.java:400)
        at org.irods.jargon.core.pub.IRODSAccessObjectFactoryImpl.authenticateIRODSAccount(IRODSAccessObjectFactoryImpl.java:81)
        at com.emc.metalnx.jobs.SyncJobs.authenticateIRODSAccount(SyncJobs.java:237)
        at com.emc.metalnx.jobs.SyncJobs.sync(SyncJobs.java:76)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:65)
        at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
```

Login to MetaLnx ist possible.

**Comment by ajguerra** [comment]
Are you trying to use authenticate as `rods` or another user?

**Comment by kuntzagk** [comment]
The exception is thrown at startup of Metalnx before trying to authenticate.
I can still authenticate later on.

**Comment by ajguerra** [comment]
login to Metalnx is still possible only for `rods` (because he's the only one using the standard auth), right?

**Comment by kuntzagk** [comment]
No, after initial setup I changed authentication from "Standard" to "PAM" since all users except `rods` use this. So after the change "rods" can NOT login anymore but everybody else can.

**Comment by ajguerra** [comment]
@kuntzagk I was able to start up Metalnx without any issues against an IRODS 4.1.9 with PAM. Let me walk you through the steps I made so you can compare with yours.

My `/etc/pam.d/irods` file looks like this (very simple):

    $ cat /etc/pam.d/irods
    auth sufficient pam_unix.so

I have created a unix user named `arthur` and created the same user into the iCAT by running `imkuser arthur rodsadmin`.

Just to be on the safe side, I made sure that I could login in iRODS with `arthur`'s account and I could.

Then, I started the Metalnx setup process. I installed the RPM package for the 1.3.0 version provided in the releases page. That done I run the setup script:

    $ python /opt/emc/setup_metalnx.py

So, 
- I pointed Metalnx where my tomcat directory was, 
- Entered my DB credentials
- Used `arthur`'s account when the scripts asks for iRODS credentials
- Set PAM as the authentication schema when the scripts asks for it

After those steps, Metalnx was able to start properly - no errors. I was able to login into the appliaction just fine like you do, but no exceptions on the logs.

Btw, everything I did was through the setup script. I didn't modify any files manually.

Is that process what you followed to set up your environment?

Tks!

**Comment by michael-conway** [comment]
For housekeeping, I'm going to close this issue as not reproduced. NB that issue #19 has been duplicated and is on the boards at NIEHS for resolution.
