### ISSUE TITLE
When I try to delete collection without permission I get success message

### ISSUE THREAD

**Issue by kuntzagk** [irods-contrib/metalnx-web#210]
When I try to delete a collection where I do not have enough permissions I get a popup saying "Success":

![metalnx_deletion_bug](https://user-images.githubusercontent.com/822870/110004805-1df1b900-7d18-11eb-82a1-4e9c37762f6b.PNG)

The collection is not deleted though.
In the Metalnx log I find a exception:

```
metalnx_1  | 2021-03-04 17:16:18 ERROR FileOperationServiceImpl:145 - Could not delete item /biomarkerPocZone/BioMarkerDataStore/12871/DNA_BEAMing_SysmexInostics:
metalnx_1  | org.irods.jargon.core.exception.CatNoAccessException: No access to item in catalog
metalnx_1  |    at org.irods.jargon.core.connection.IRODSErrorScanner.checkSpecificCodesAndThrowIfExceptionLocated(IRODSErrorScanner.java:160)
metalnx_1  |    at org.irods.jargon.core.connection.IRODSErrorScanner.inspectAndThrowIfNeeded(IRODSErrorScanner.java:115)
metalnx_1  |    at org.irods.jargon.core.connection.IRODSMidLevelProtocol.processMessageInfoLessThanZero(IRODSMidLevelProtocol.java:1542)
metalnx_1  |    at org.irods.jargon.core.connection.IRODSMidLevelProtocol.readMessage(IRODSMidLevelProtocol.java:1046)
metalnx_1  |    at org.irods.jargon.core.connection.IRODSMidLevelProtocol.readMessage(IRODSMidLevelProtocol.java:1014)
metalnx_1  |    at org.irods.jargon.core.connection.IRODSMidLevelProtocol.irodsFunction(IRODSMidLevelProtocol.java:427)
metalnx_1  |    at org.irods.jargon.core.connection.IRODSMidLevelProtocol.irodsFunction(IRODSMidLevelProtocol.java:553)
metalnx_1  |    at org.irods.jargon.core.pub.IRODSFileSystemAOImpl.directoryDeleteNoForce(IRODSFileSystemAOImpl.java:1083)
metalnx_1  |    at com.emc.metalnx.services.irods.FileOperationServiceImpl.deleteItem(FileOperationServiceImpl.java:120)
metalnx_1  |    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
metalnx_1  |    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
metalnx_1  |    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
metalnx_1  |    at java.base/java.lang.reflect.Method.invoke(Method.java:566)
metalnx_1  |    at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:333)
metalnx_1  |    at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:190)
metalnx_1  |    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
metalnx_1  |    at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:99)
metalnx_1  |    at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:282)
metalnx_1  |    at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96)
metalnx_1  |    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
metalnx_1  |    at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:213)
metalnx_1  |    at com.sun.proxy.$Proxy56.deleteItem(Unknown Source)
metalnx_1  |    at com.emc.metalnx.controller.FileOperationsController.deleteCollectionAndDataObject(FileOperationsController.java:329)
metalnx_1  |    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
metalnx_1  |    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
metalnx_1  |    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
metalnx_1  |    at java.base/java.lang.reflect.Method.invoke(Method.java:566)
metalnx_1  |    at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205)
metalnx_1  |    at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:133)
metalnx_1  |    at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:97)
metalnx_1  |    at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:827)
metalnx_1  |    at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:738)
metalnx_1  |    at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85)
metalnx_1  |    at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:967)
metalnx_1  |    at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:901)
metalnx_1  |    at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)
metalnx_1  |    at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:872)
metalnx_1  |    at javax.servlet.http.HttpServlet.service(HttpServlet.java:652)
metalnx_1  |    at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)
metalnx_1  |    at javax.servlet.http.HttpServlet.service(HttpServlet.java:733)
metalnx_1  |    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227)
metalnx_1  |    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
metalnx_1  |    at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
metalnx_1  |    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
metalnx_1  |    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
metalnx_1  |    at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330)
metalnx_1  |    at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:118)
metalnx_1  |    at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:84)
metalnx_1  |    at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
metalnx_1  |    at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:113)
metalnx_1  |    at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
metalnx_1  |    at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:103)
metalnx_1  |    at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
metalnx_1  |    at org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:113)
metalnx_1  |    at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
metalnx_1  |    at org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:154)
metalnx_1  |    at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
metalnx_1  |    at org.springframework.security.web.savedrequest.RequestCacheAwareFilter.doFilter(RequestCacheAwareFilter.java:45)
metalnx_1  |    at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
metalnx_1  |    at org.springframework.security.web.authentication.www.BasicAuthenticationFilter.doFilter(BasicAuthenticationFilter.java:150)
metalnx_1  |    at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
metalnx_1  |    at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:199)
metalnx_1  |    at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
metalnx_1  |    at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:110)
metalnx_1  |    at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
metalnx_1  |    at org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:50)
metalnx_1  |    at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
metalnx_1  |    at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
metalnx_1  |    at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:87)
metalnx_1  |    at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
metalnx_1  |    at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:192)
metalnx_1  |    at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:160)
metalnx_1  |    at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:347)
metalnx_1  |    at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:263)
metalnx_1  |    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
metalnx_1  |    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
metalnx_1  |    at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:197)
metalnx_1  |    at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
metalnx_1  |    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
metalnx_1  |    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
metalnx_1  |    at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
metalnx_1  |    at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
metalnx_1  |    at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:667)
metalnx_1  |    at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:143)
metalnx_1  |    at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
metalnx_1  |    at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:687)
metalnx_1  |    at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
metalnx_1  |    at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:346)
metalnx_1  |    at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:374)
metalnx_1  |    at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
metalnx_1  |    at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:887)
metalnx_1  |    at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1684)
metalnx_1  |    at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
metalnx_1  |    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
metalnx_1  |    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
metalnx_1  |    at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
metalnx_1  |    at java.base/java.lang.Thread.run(Thread.java:834)
```

The code in jargon-irods-ext FileOperationServiceImpl.java only logs the exception without informing caller.

https://github.com/DICE-UNC/jargon-irods-ext/blob/9e502ba116c714a7fbbc0151708a5055a448f66c/emc-metalnx-services/src/main/java/com/emc/metalnx/services/irods/FileOperationServiceImpl.java

**Comment by trel** [comment]
Good find.
