### ISSUE TITLE
HTTPS issue with metalnx-web

### ISSUE THREAD

**Issue by aiteteji** [irods-contrib/metalnx-web#30]
Hello All,

irods works successfully with https on the command line. I could also connect through irods client server but even though the metalnx installation completed without errors, I could not access it with the given https link.

Here are my logs

irods:
```
# tail  /var/lib/irods/iRODS/server/log/rodsLog.2018.01.16

Jan 19 11:51:45 pid:11175 NOTICE: Agent process 1722 started for puser=rods and cuser=rods from 172.20.14.6
Jan 19 11:51:45 pid:1722 NOTICE: readAndProcClientMsg: received disconnect msg from client
Jan 19 11:51:45 pid:1722 NOTICE: Agent exiting with status = 0
Jan 19 11:51:45 pid:11175 NOTICE: Agent process 1722 exited with status 0
Jan 19 11:51:47 pid:11175 NOTICE: Agent process 1725 started for puser=rods and cuser=rods from 172.20.14.6
Jan 19 11:51:47 pid:1725 NOTICE: readAndProcClientMsg: received disconnect msg from client
Jan 19 11:51:47 pid:1725 NOTICE: Agent exiting with status = 0
Jan 19 11:51:47 pid:11175 NOTICE: Agent process 1725 exited with status 0
Jan 19 12:37:58 pid:11175 NOTICE: Agent process 2365 started for puser=rods and cuser=rods from 172.20.14.6
Jan 19 12:37:59 pid:2365 NOTICE: readAndProcClientMsg: received disconnect msg from client
Jan 19 12:37:59 pid:2365 NOTICE: Agent exiting with status = 0
Jan 19 12:37:59 pid:11175 NOTICE: Agent process 2365 exited with status 0
Jan 19 12:39:17 pid:11175 NOTICE: Agent process 2430 started for puser=rods and cuser=rods from 172.20.14.6
Jan 19 13:12:49 pid:2430 ERROR: [-]     iRODS/server/core/src/rsApiHandler.cpp:522:readAndProcClientMsg :  status [SYS_HEADER_READ_LEN_ERR]  errno [] -- message []
        [-]     iRODS/lib/core/src/sockComm.cpp:199:readMsgHeader :  status [SYS_HEADER_READ_LEN_ERR]  errno [] -- message [failed to call 'read header']
                [-]     libssl.cpp:577:ssl_read_msg_header :  status [SYS_HEADER_READ_LEN_ERR]  errno [] -- message [read 0 expected 4]

Jan 19 13:12:49 pid:2430 ERROR: [-]     iRODS/server/core/src/rodsAgent.cpp:256:main :  status [SSL_SHUTDOWN_ERROR]  errno [] -- message []
        [-]     iRODS/lib/core/src/sockComm.cpp:162:sockAgentStop :  status [SSL_SHUTDOWN_ERROR]  errno [] -- message [failed to call 'agent stop']
                [-]     libssl.cpp:945:ssl_agent_stop :  status [SSL_SHUTDOWN_ERROR]  errno [] -- message [error completing shutdown of SSL connection]

Jan 19 13:12:49 pid:11175 NOTICE: Agent process 2430 exited with status 16384
Jan 19 13:13:03 pid:11175 NOTICE: Agent process 3116 started for puser=rods and cuser=rods from 172.20.14.6
    LocalHostName:  localhost, irods-srvr, Port Num: 1247.

Jan 19 13:16:21 pid:1234 NOTICE:    RescName: bundleResc, VaultPath: /bundle
Zone Info:
    ZoneName: D**Mo**   Type: LOCAL_ICAT    HostAddr: localhost   PortNum: 1247

reHost:   localhost

Jan 19 13:16:21 pid:1234 NOTICE: rodsServer Release version rods4.1.11 - API Version d is up
Jan 19 13:16:21 pid:1236 NOTICE: Starting irodsReServer
Jan 19 13:16:21 pid:1234 NOTICE: >>> control plane :: listening on port 1248
Jan 19 13:16:43 pid:1234 NOTICE: Agent process 1405 started for puser=rods and cuser=rods from 172.20.14.6
Jan 22 08:42:46 pid:1405 ERROR: [-]     iRODS/server/core/src/rsApiHandler.cpp:522:readAndProcClientMsg :  status [SYS_HEADER_READ_LEN_ERR]  errno [] -- message []
        [-]     iRODS/lib/core/src/sockComm.cpp:199:readMsgHeader :  status [SYS_HEADER_READ_LEN_ERR]  errno [] -- message [failed to call 'read header']
                [-]     libssl.cpp:577:ssl_read_msg_header :  status [SYS_HEADER_READ_LEN_ERR]  errno [] -- message [read 0 expected 4]

Jan 22 08:42:46 pid:1405 ERROR: [-]     iRODS/server/core/src/rodsAgent.cpp:256:main :  status [SSL_SHUTDOWN_ERROR]  errno [] -- message []
        [-]     iRODS/lib/core/src/sockComm.cpp:162:sockAgentStop :  status [SSL_SHUTDOWN_ERROR]  errno [] -- message [failed to call 'agent stop']
                [-]     libssl.cpp:945:ssl_agent_stop :  status [SSL_SHUTDOWN_ERROR]  errno [] -- message [error completing shutdown of SSL connection]

Jan 22 08:42:47 pid:1234 NOTICE: Agent process 1405 exited with status 16384
Jan 22 08:43:01 pid:1234 NOTICE: Agent process 22604 started for puser=rods and cuser=rods from 172.20.14.6
Jan 22 13:19:36 pid:1234 NOTICE: Agent process 26959 started for puser=rods and cuser=rods from 172.20.14.6
Jan 22 13:19:36 pid:26959 NOTICE: readAndProcClientMsg: received disconnect msg from client
Jan 22 13:19:36 pid:26959 NOTICE: Agent exiting with status = 0
Jan 22 13:19:36 pid:1234 NOTICE: Agent process 26959 exited with status 0
Jan 22 13:19:37 pid:1234 NOTICE: Agent process 26963 started for puser=rods and cuser=rods from 172.20.14.6
Jan 22 13:19:38 pid:26963 NOTICE: readAndProcClientMsg: received disconnect msg from client
Jan 22 13:19:38 pid:26963 NOTICE: Agent exiting with status = 0
Jan 22 13:19:38 pid:1234 NOTICE: Agent process 26963 exited with status 0
 status [SYS_HEADER_READ_LEN_ERR]  errno [] -- message [failed to call 'read header']
` 
Catalina log:
`22-Jan-2018 12:04:41.301 INFO [http-nio-0.0.0.0-8080-exec-5] org.apache.coyote.http11.Http11Processor.service Error parsing HTTP request header
 Note: further occurrences of HTTP header parsing errors will be logged at DEBUG level.
 java.lang.IllegalArgumentException: Invalid character found in method name. HTTP method names must be tokens
        at org.apache.coyote.http11.Http11InputBuffer.parseRequestLine(Http11InputBuffer.java:426)
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:687)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:790)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1459)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:748)

22-Jan-2018 14:38:40.167 INFO [main] org.apache.catalina.core.StandardServer.await A valid shutdown command was received via the shutdown port. Stopping the Server instance.
22-Jan-2018 14:38:40.170 INFO [main] org.apache.coyote.AbstractProtocol.pause Pausing ProtocolHandler ["http-nio-0.0.0.0-8080"]
22-Jan-2018 14:38:40.175 INFO [main] org.apache.coyote.AbstractProtocol.pause Pausing ProtocolHandler ["https-openssl-nio-8443"]
22-Jan-2018 14:38:40.177 INFO [main] org.apache.catalina.core.StandardService.stopInternal Stopping service [Catalina]
22-Jan-2018 14:38:40.290 WARNING [localhost-startStop-2] org.apache.catalina.loader.WebappClassLoaderBase.clearReferencesJdbc The web application [emc-metalnx-web] registered the JDBC dri$
22-Jan-2018 14:38:40.316 INFO [main] org.apache.coyote.AbstractProtocol.stop Stopping ProtocolHandler ["http-nio-0.0.0.0-8080"]
22-Jan-2018 14:38:40.333 INFO [main] org.apache.coyote.AbstractProtocol.stop Stopping ProtocolHandler ["https-openssl-nio-8443"]
22-Jan-2018 14:38:40.342 INFO [main] org.apache.coyote.AbstractProtocol.destroy Destroying ProtocolHandler ["http-nio-0.0.0.0-8080"]
22-Jan-2018 14:38:40.343 INFO [main] org.apache.coyote.AbstractProtocol.destroy Destroying ProtocolHandler ["https-openssl-nio-8443"]
22-Jan-2018 14:38:41.083 WARNING [main] org.apache.coyote.http11.Http11Protocol.<init> The HTTP BIO connector has been removed in Tomcat 8.5.x onwards. The HTTP BIO connector configuratio$
22-Jan-2018 14:38:41.108 WARNING [main] org.apache.catalina.startup.SetAllPropertiesRule.begin [SetAllPropertiesRule]{Server/Service/Connector} Setting property 'accceptCount' to '100' di$
22-Jan-2018 14:38:41.108 WARNING [main] org.apache.catalina.startup.SetAllPropertiesRule.begin [SetAllPropertiesRule]{Server/Service/Connector} Setting property 'disableUploadTiemout' to $
22-Jan-2018 14:38:41.246 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server version:        Apache Tomcat/8.5.24
22-Jan-2018 14:38:41.246 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server built:          Nov 27 2017 13:05:30 UTC
22-Jan-2018 14:38:41.247 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server number:         8.5.24.0
22-Jan-2018 14:38:41.247 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log OS Name:               Linux
22-Jan-2018 14:38:41.247 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log OS Version:            3.13.0-135-generic
22-Jan-2018 14:38:41.247 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Architecture:          amd64
22-Jan-2018 14:38:41.247 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Java Home:             /usr/lib/jvm/java-8-oracle/jre
22-Jan-2018 14:38:41.248 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log JVM Version:           1.8.0_151-b12
22-Jan-2018 14:38:41.248 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log JVM Vendor:            Oracle Corporation
22-Jan-2018 14:38:41.248 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log CATALINA_BASE:         /opt/tomcat
22-Jan-2018 14:38:41.248 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log CATALINA_HOME:         /opt/tomcat
22-Jan-2018 14:38:41.249 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.util.logging.config.file=/opt/tomcat/conf/logging.properties
22-Jan-2018 14:38:41.249 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager
22-Jan-2018 14:38:41.249 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.awt.headless=true
22-Jan-2018 14:38:41.249 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -XX:+DisableExplicitGC
22-Jan-2018 14:38:41.249 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -XX:+UseParallelOldGC
22-Jan-2018 14:38:41.250 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Xms256m
22-Jan-2018 14:38:41.250 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Xmx2g
22-Jan-2018 14:38:41.250 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.security.egd=file:/dev/./urandom
22-Jan-2018 14:38:41.250 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djavax.net.ssl.trustStore=/etc/irods/ssl/irodskeystore
22-Jan-2018 14:38:41.250 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djavax.net.ssl.trustStorePassword=testpassword
22-Jan-2018 14:38:41.251 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djdk.tls.ephemeralDHKeySize=2048
22-Jan-2018 14:38:41.251 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.protocol.handler.pkgs=org.apache.catalina.webresources
22-Jan-2018 14:38:41.251 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dignore.endorsed.dirs=
22-Jan-2018 14:38:41.251 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dcatalina.base=/opt/tomcat
22-Jan-2018 14:38:41.251 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dcatalina.home=/opt/tomcat

22-Jan-2018 14:38:41.251 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.io.tmpdir=/opt/tomcat/temp
22-Jan-2018 14:38:41.252 INFO [main] org.apache.catalina.core.AprLifecycleListener.lifecycleEvent Loaded APR based Apache Tomcat Native library [1.2.16] using APR version [1.6.3].
22-Jan-2018 14:38:41.252 INFO [main] org.apache.catalina.core.AprLifecycleListener.lifecycleEvent APR capabilities: IPv6 [true], sendfile [true], accept filters [false], random [true].
22-Jan-2018 14:38:41.252 INFO [main] org.apache.catalina.core.AprLifecycleListener.lifecycleEvent APR/OpenSSL configuration: useAprConnector [false], useOpenSSL [true]
22-Jan-2018 14:38:41.266 INFO [main] org.apache.catalina.core.AprLifecycleListener.initializeSSL OpenSSL successfully initialized [OpenSSL 1.0.1f 6 Jan 2014]
22-Jan-2018 14:38:41.475 INFO [main] org.apache.coyote.AbstractProtocol.init Initializing ProtocolHandler ["https-openssl-nio-8443"]
22-Jan-2018 14:38:41.834 INFO [main] org.apache.tomcat.util.net.NioSelectorPool.getSharedSelector Using a shared selector for servlet write/read
22-Jan-2018 14:38:41.846 INFO [main] org.apache.catalina.startup.Catalina.load Initialization processed in 1288 ms
22-Jan-2018 14:38:41.886 INFO [main] org.apache.catalina.core.StandardService.startInternal Starting service [Catalina]
22-Jan-2018 14:38:41.886 INFO [main] org.apache.catalina.core.StandardEngine.startInternal Starting Servlet Engine: Apache Tomcat/8.5.24
22-Jan-2018 14:38:41.904 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDescriptor Deploying configuration descriptor [/opt/tomcat/conf/Catalina/localhost/manager.xml]
22-Jan-2018 14:38:41.948 WARNING [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDescriptor A docBase [/opt/tomcat/webapps/manager] inside the host appBase has been specified, and will be ignored
22-Jan-2018 14:38:42.393 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDescriptor Deployment of configuration descriptor [/opt/tomcat/conf/Catalina/localhost/manager.xml] has finished in [489] ms
22-Jan-2018 14:38:42.395 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deploying web application directory [/opt/tomcat/webapps/emc-metalnx-web]
22-Jan-2018 14:38:46.235 INFO [localhost-startStop-1] org.apache.jasper.servlet.TldScanner.scanJars At least one JAR was scanned for TLDs yet contained no TLDs. Enable debug logging for this logger for a complete list of JARs that were scanned but no TLDs were found in them. Skipping unneeded JARs during scanning can improve startup time and JSP compilation time.
22-Jan-2018 14:38:54.362 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deployment of web application directory [/opt/tomcat/webapps/emc-metalnx-web] has finished in [11,967] ms
22-Jan-2018 14:38:54.374 INFO [main] org.apache.coyote.AbstractProtocol.start Starting ProtocolHandler ["https-openssl-nio-8443"]
22-Jan-2018 14:38:54.404 INFO [main] org.apache.catalina.startup.Catalina.start Server startup in 12557 ms
```

hope someone can help.

**Comment by michael-conway** [comment]
I wonder what rodsLog shows? I would look first to see if this is an SSL
handshake/config error.

**Comment by aiteteji** [comment]
Hi Michael,
Thanks for the reply. The first part of the log above is my rodsLog. It gave [SYS_HEADER_READ_LEN_ERR] and  [SSL_SHUTDOWN_ERROR].

**Comment by trel** [comment]
closing this - SSL confirmed to work with good configuration
