### ISSUE TITLE
Clicking on the rules icon in the left menu starts a repeating loop of rules page refreshes.

### ISSUE THREAD

**Issue by sgworth** [irods-contrib/metalnx-web#54]

**Comment by michael-conway** [comment]
on it..gonna try and clear some of this today!

**Comment by deeppatelcs** [comment]
@sgworth @michael-conway 
It is because it is not able to find ".rulecache"  collection at location: /irodsZone/.rulecache
Creating ".rulecache" collection under irodsZone should fix it.

**Comment by michael-conway** [comment]
nice, we should just add a mkdir for this on startup using the rods
account, that will be idempotent anyhow

**Comment by sgworth** [comment]
That works.  Creating .rulecache as irods at the top level zone
(tempZone for the default) corrects this.
Did it manually and the problem went away.

**Comment by sgworth** [comment]
I just checked the old python setup script in the 1.4 branch and the rule microservice files. I do not see where this file gets created in the old version.  It may have been an oversight.

**Comment by michael-conway** [comment]
logs when zone/.rulecache deleted to replicate issue

```

2018-06-24 12:39:04 INFO  AbstractIRODSMidLevelProtocolFactory:98 - ..authenticated...now decorate and return...
2018-06-24 12:39:04 INFO  AbstractIRODSMidLevelProtocolFactory:145 - decorate()
2018-06-24 12:39:04 INFO  EnvironmentalInfoAccessor:44 - getting irods server properties
2018-06-24 12:39:04 INFO  DiscoveredServerPropertiesCache:85 - now retriving server properties from cache with zone:zone1
2018-06-24 12:39:04 INFO  EnvironmentalInfoAccessor:54 - returning cached props:org.irods.jargon.core.connection.IRODSServerProperties@3b46d15f
2018-06-24 12:39:04 INFO  AbstractIRODSMidLevelProtocolFactory:167 - org.irods.jargon.core.connection.IRODSServerProperties@3b46d15f
2018-06-24 12:39:04 INFO  CollectionAndDataObjectListAndSearchAOImpl:275 - listDataObjectsAndCollectionsUnderPath()
2018-06-24 12:39:04 INFO  CollectionAndDataObjectListAndSearchAOImpl:281 - absolutePathToParent:/zone1/.rulecache
2018-06-24 12:39:04 INFO  CollectionListingUtils:1067 - got a file not found, try to heuristically produce an objstat
2018-06-24 12:39:04 INFO  CollectionListingUtils:163 - handleNoObjStatUnderRootOrHomeByLookingForPublicAndHome()
2018-06-24 12:39:04 INFO  CollectionListingUtils:233 - under zone, add a home obj stat
2018-06-24 12:39:04 INFO  CollectionListingUtils:250 - really is a not found for file:/zone1/.rulecache
2018-06-24 12:39:04 INFO  CollectionAndDataObjectListAndSearchAOImpl:289 - didn't find an objStat for the path, account for cases where there are strict acls and give Jargon a chance to drill down to a place where the user has permissions
2018-06-24 12:39:04 INFO  CollectionListingUtils:83 - handleNoListingUnderRootOrHomeByLookingForPublicAndHome()
2018-06-24 12:39:04 INFO  CollectionListingUtils:143 - really is a not found for file:/zone1/.rulecache
2018-06-24 12:39:04 ERROR CollectionServiceImpl:391 - Could not locate file: 
org.irods.jargon.core.exception.FileNotFoundException: unable to find file under path
	at org.irods.jargon.core.pub.CollectionListingUtils.handleNoListingUnderRootOrHomeByLookingForPublicAndHome(CollectionListingUtils.java:144)
	at org.irods.jargon.core.pub.CollectionAndDataObjectListAndSearchAOImpl.listDataObjectsAndCollectionsUnderPath(CollectionAndDataObjectListAndSearchAOImpl.java:291)
	at com.emc.metalnx.services.irods.CollectionServiceImpl.getSubCollectionsAndDataObjectsUnderPath(CollectionServiceImpl.java:384)
	at sun.reflect.GeneratedMethodAccessor162.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:333)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:190)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:99)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:282)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:213)
	at com.sun.proxy.$Proxy52.getSubCollectionsAndDataObjectsUnderPath(Unknown Source)
	at com.emc.metalnx.controller.BrowseController.getPaginatedJSONObjs(BrowseController.java:765)
	at sun.reflect.GeneratedMethodAccessor161.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:133)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:116)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:827)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:738)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:963)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:897)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:861)



```

**Comment by michael-conway** [comment]
added auto-create of rulecache if not present in the RuleDeploymentService
